name: plant_care_system
description: "Plant Care App"

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.4.0
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false  # Change this to false
  image_path: "assets/icons/plant_icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icons/plant_icon.png"
  min_sdk_android: 21





